stages:
  preprocess:
    cmd: python3 src/preprocess.py
    deps:
      - data/raw
    outs:
      - data/processed
  train:
    cmd: python3 src/train.py --params params.yaml
    deps:
      - data/processed
      - src/train.py
      - params.yaml
    outs:
      - mlruns
      - models